### ISSUE TITLE
It doesn't work for remotes ansible hosts

### ISSUE THREAD

**Issue by sguarin** [iesplin/ansible-playbook-kali#2]
It would be great to get this work against an inventory of remote kali machines.
Things that must be modified in order to make this possible:
1. Remote user must be parametrized instead of lookup from env.
```
kali_user: "{{ lookup('env','USER') }}"
```
2. Define using a .a4k_config per host locally or remote in the host.
3. Issue with DISPLAY variable on some tasks.

**Comment by iesplin** [comment]
Thanks for the interest, however this project is oriented towards my own use case, which is for automating the configuration of local Kali VMs. 
Many of the tools and configurations I've added are my own preferences and won't meet everyone's needs. This is the main reason that this repo is public and has been given an MIT license - so others are free to fork and change it to meet their own needs.
